package com.goldengekko.meetr.dao;

import java.util.HashMap;
import java.util.Map;
import net.sf.mardao.core.dao.DaoImpl;
import com.goldengekko.meetr.domain.DmFile;
import com.goldengekko.meetr.domain.DmContact;
import com.goldengekko.meetr.domain.DmMeeting;
import com.goldengekko.meetr.domain.DmTask;
import com.goldengekko.meetr.domain.DmAgendaItem;
import com.goldengekko.meetr.domain.DmAccount;

/**
 * Context to define the Dao beans.
 * This file is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-09-30T18:18:09.100+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DaoConfig {

    public static Map<Class, DaoImpl> createDaos() {
        final HashMap<Class, DaoImpl> map = new HashMap<Class, DaoImpl>();

        // first, create and map Dao instances:
        final DmFileDaoBean dmFileDao =
            new DmFileDaoBean();
        map.put(DmFile.class, dmFileDao);
        final DmContactDaoBean dmContactDao =
            new DmContactDaoBean();
        map.put(DmContact.class, dmContactDao);
        final DmMeetingDaoBean dmMeetingDao =
            new DmMeetingDaoBean();
        map.put(DmMeeting.class, dmMeetingDao);
        final DmTaskDaoBean dmTaskDao =
            new DmTaskDaoBean();
        map.put(DmTask.class, dmTaskDao);
        final DmAgendaItemDaoBean dmAgendaItemDao =
            new DmAgendaItemDaoBean();
        map.put(DmAgendaItem.class, dmAgendaItemDao);
        final DmAccountDaoBean dmAccountDao =
            new DmAccountDaoBean();
        map.put(DmAccount.class, dmAccountDao);

        // next, wire parents;

        // finally, wire many-to-ones;
	
        return map;
    }
}